version: "3.8"

services:
  app:
    restart: unless-stopped
    stdin_open: true
    environment:
      - NODE_ENV=PRODUCTION
    build: ./app
    ports:
      - "5173:5173"

  landing:
    build: ./landing
    ports:
      - "3001:3001"
