export default [
    {
        Name: 'Derrick Henry',
        Team: 'TEN',
        Number: 22,
        AverageDraftPosition: 2.3,
        FantasyPoints: 253.46,
        inner_color: '#4B92DB',
        outer_color: '#002244',
        team_name: 'Tennessee Titans',
    },
    {
        Name: 'Christian McCaffrey',
        Team: 'CAR',
        Number: 22,
        AverageDraftPosition: 2.6,
        FantasyPoints: 233.98,
        inner_color: '#0085CA',
        outer_color: '#000000',
        team_name: 'Carolina Panthers',
    },
    {
        Name: 'Dalvin Cook',
        Team: 'MIN',
        Number: 4,
        AverageDraftPosition: 4.2,
        FantasyPoints: 225.22,
        inner_color: '#FFC62F',
        outer_color: '#4F2683',
        team_name: 'Minnesota Vikings',
    },
    {
        Name: 'Cooper Kupp',
        Team: 'LAR',
        Number: 10,
        AverageDraftPosition: 4.9,
        FantasyPoints: 219.08,
        inner_color: '#FFD100',
        outer_color: '#003594',
        team_name: 'Los Angeles Rams',
    },
    {
        Name: 'Justin Jefferson',
        Team: 'MIN',
        Number: 18,
        AverageDraftPosition: 5.4,
        FantasyPoints: 199.63,
        inner_color: '#FFC62F',
        outer_color: '#4F2683',
        team_name: 'Minnesota Vikings',
    },
    {
        Name: 'Nick Chubb',
        Team: 'CLE',
        Number: 24,
        AverageDraftPosition: 7.1,
        FantasyPoints: 201.51,
        inner_color: '#FF3300',
        outer_color: '#311D00',
        team_name: 'Cleveland Browns',
    },
    {
        Name: 'Austin Ekeler',
        Team: 'LAC',
        Number: 30,
        AverageDraftPosition: 7.2,
        FantasyPoints: 232.39,
        inner_color: '#FFC20E',
        outer_color: '#0080C6',
        team_name: 'Los Angeles Chargers',
    },
    {
        Name: "Ja'Marr Chase",
        Team: 'CIN',
        Number: 1,
        AverageDraftPosition: 7.5,
        FantasyPoints: 195.46,
        inner_color: '#FB4F14',
        outer_color: '#000000',
        team_name: 'Cincinnati Bengals',
    },
    {
        Name: 'Najee Harris',
        Team: 'PIT',
        Number: 22,
        AverageDraftPosition: 9.6,
        FantasyPoints: 213.94,
        inner_color: '#FFB612',
        outer_color: '#000000',
        team_name: 'Pittsburgh Steelers',
    },
    {
        Name: "D'Andre Swift",
        Team: 'DET',
        Number: 32,
        AverageDraftPosition: 10.3,
        FantasyPoints: 187.93,
        inner_color: '#B0B7BC',
        outer_color: '#0076B6',
        team_name: 'Detroit Lions',
    },
    {
        Name: 'Stefon Diggs',
        Team: 'BUF',
        Number: 14,
        AverageDraftPosition: 12,
        FantasyPoints: 178.29,
        inner_color: '#C60C30',
        outer_color: '#00338D',
        team_name: 'Buffalo Bills',
    },
    {
        Name: 'Davante Adams',
        Team: 'LV',
        Number: 17,
        AverageDraftPosition: 13,
        FantasyPoints: 182,
        inner_color: '#000000',
        outer_color: '#A5ACAF',
        team_name: 'Las Vegas Raiders',
    },
    {
        Name: 'Alvin Kamara',
        Team: 'NO',
        Number: 41,
        AverageDraftPosition: 13.1,
        FantasyPoints: 202.71,
        inner_color: '#D3BC8D',
        outer_color: '#000000',
        team_name: 'New Orleans Saints',
    },
    {
        Name: 'Aaron Jones',
        Team: 'GB',
        Number: 33,
        AverageDraftPosition: 14.6,
        FantasyPoints: 191.38,
        inner_color: '#FFB612',
        outer_color: '#203731',
        team_name: 'Green Bay Packers',
    },
    {
        Name: 'Joe Mixon',
        Team: 'CIN',
        Number: 28,
        AverageDraftPosition: 15.7,
        FantasyPoints: 221.41,
        inner_color: '#FB4F14',
        outer_color: '#000000',
        team_name: 'Cincinnati Bengals',
    },
    {
        Name: 'Travis Kelce',
        Team: 'KC',
        Number: 87,
        AverageDraftPosition: 16.1,
        FantasyPoints: 158.58,
        inner_color: '#FFB612',
        outer_color: '#E31837',
        team_name: 'Kansas City Chiefs',
    },
    {
        Name: 'Javonte Williams',
        Team: 'DEN',
        Number: 33,
        AverageDraftPosition: 16.6,
        FantasyPoints: 195.05,
        inner_color: '#0A2343',
        outer_color: '#FC4C02',
        team_name: 'Denver Broncos',
    },
    {
        Name: 'Josh Allen',
        Team: 'BUF',
        Number: 17,
        AverageDraftPosition: 17,
        FantasyPoints: 377.07,
        inner_color: '#C60C30',
        outer_color: '#00338D',
        team_name: 'Buffalo Bills',
    },
    {
        Name: 'Saquon Barkley',
        Team: 'NYG',
        Number: 26,
        AverageDraftPosition: 18.8,
        FantasyPoints: 195.45,
        inner_color: '#A71930',
        outer_color: '#0B2265',
        team_name: 'New York Giants',
    },
    {
        Name: 'CeeDee Lamb',
        Team: 'DAL',
        Number: 88,
        AverageDraftPosition: 20.3,
        FantasyPoints: 168.13,
        inner_color: '#B0B7BC',
        outer_color: '#002244',
        team_name: 'Dallas Cowboys',
    },
    {
        Name: 'Mike Evans',
        Team: 'TB',
        Number: 13,
        AverageDraftPosition: 22.5,
        FantasyPoints: 169.9,
        inner_color: 'white',
        outer_color: '#A71930',
        team_name: 'Tampa Bay Buccaneers',
    },
    {
        Name: 'Leonard Fournette',
        Team: 'TB',
        Number: 7,
        AverageDraftPosition: 22.8,
        FantasyPoints: 197.55,
        inner_color: 'white',
        outer_color: '#A71930',
        team_name: 'Tampa Bay Buccaneers',
    },
    {
        Name: 'Tyreek Hill',
        Team: 'MIA',
        Number: 10,
        AverageDraftPosition: 23,
        FantasyPoints: 161.46,
        inner_color: '#FC4C02',
        outer_color: '#008E97',
        team_name: 'Miami Dolphins',
    },
    {
        Name: 'Ezekiel Elliott',
        Team: 'DAL',
        Number: 21,
        AverageDraftPosition: 25,
        FantasyPoints: 175.03,
        inner_color: '#B0B7BC',
        outer_color: '#002244',
        team_name: 'Dallas Cowboys',
    },
    {
        Name: 'Mark Andrews',
        Team: 'BAL',
        Number: 89,
        AverageDraftPosition: 25.7,
        FantasyPoints: 157.23,
        inner_color: 'white',
        outer_color: '#24135F',
        team_name: 'Baltimore Ravens',
    },
    {
        Name: 'A.J. Brown',
        Team: 'PHI',
        Number: 11,
        AverageDraftPosition: 25.7,
        FantasyPoints: 161.81,
        inner_color: '#A2AAAD',
        outer_color: '#004851',
        team_name: 'Philadelphia Eagles',
    },
    {
        Name: 'Deebo Samuel',
        Team: 'SF',
        Number: 19,
        AverageDraftPosition: 26.4,
        FantasyPoints: 187.18,
        inner_color: '#B3995D',
        outer_color: '#AA0000',
        team_name: 'San Francisco 49ers',
    },
    {
        Name: 'James Conner',
        Team: 'ARI',
        Number: 6,
        AverageDraftPosition: 28.1,
        FantasyPoints: 199.31,
        inner_color: '#FFFFFF',
        outer_color: '#97233F',
        team_name: 'Arizona Cardinals',
    },
    {
        Name: 'Cam Akers',
        Team: 'LAR',
        Number: 3,
        AverageDraftPosition: 28.8,
        FantasyPoints: 169.93,
        inner_color: '#FFD100',
        outer_color: '#003594',
        team_name: 'Los Angeles Rams',
    },
    {
        Name: 'Keenan Allen',
        Team: 'LAC',
        Number: 13,
        AverageDraftPosition: 29.7,
        FantasyPoints: 149.9,
        inner_color: '#FFC20E',
        outer_color: '#0080C6',
        team_name: 'Los Angeles Chargers',
    },
    {
        Name: 'Michael Pittman Jr.',
        Team: 'IND',
        Number: 11,
        AverageDraftPosition: 32.2,
        FantasyPoints: 149.19,
        inner_color: '#FFFFFF',
        outer_color: '#013369',
        team_name: 'Indianapolis Colts',
    },
    {
        Name: 'David Montgomery',
        Team: 'CHI',
        Number: 32,
        AverageDraftPosition: 32.4,
        FantasyPoints: 170.31,
        inner_color: '#E64100',
        outer_color: '#0B162A',
        team_name: 'Chicago Bears',
    },
    {
        Name: 'Tee Higgins',
        Team: 'CIN',
        Number: 85,
        AverageDraftPosition: 32.9,
        FantasyPoints: 162.16,
        inner_color: '#FB4F14',
        outer_color: '#000000',
        team_name: 'Cincinnati Bengals',
    },
    {
        Name: 'Kyle Pitts',
        Team: 'ATL',
        Number: 8,
        AverageDraftPosition: 34.3,
        FantasyPoints: 132.95,
        inner_color: '#A71930',
        outer_color: '#000000',
        team_name: 'Atlanta Falcons',
    },
    {
        Name: 'J.K. Dobbins',
        Team: 'BAL',
        Number: 27,
        AverageDraftPosition: 34.7,
        FantasyPoints: 166.97,
        inner_color: 'white',
        outer_color: '#24135F',
        team_name: 'Baltimore Ravens',
    },
    {
        Name: 'Elijah Mitchell',
        Team: 'SF',
        Number: 25,
        AverageDraftPosition: 35.2,
        FantasyPoints: 173.46,
        inner_color: '#B3995D',
        outer_color: '#AA0000',
        team_name: 'San Francisco 49ers',
    },
    {
        Name: 'Terry McLaurin',
        Team: 'WAS',
        Number: 17,
        AverageDraftPosition: 36.3,
        FantasyPoints: 146.34,
        inner_color: '#FFB612',
        outer_color: '#5A1414',
        team_name: 'Washington Commanders',
    },
    {
        Name: 'Antonio Gibson',
        Team: 'WAS',
        Number: 24,
        AverageDraftPosition: 38.1,
        FantasyPoints: 154.98,
        inner_color: '#FFB612',
        outer_color: '#5A1414',
        team_name: 'Washington Commanders',
    },
    {
        Name: 'George Kittle',
        Team: 'SF',
        Number: 85,
        AverageDraftPosition: 39.1,
        FantasyPoints: 113.76,
        inner_color: '#B3995D',
        outer_color: '#AA0000',
        team_name: 'San Francisco 49ers',
    },
    {
        Name: 'Lamar Jackson',
        Team: 'BAL',
        Number: 8,
        AverageDraftPosition: 39.4,
        FantasyPoints: 335.75,
        inner_color: 'white',
        outer_color: '#24135F',
        team_name: 'Baltimore Ravens',
    },
    {
        Name: 'Jalen Hurts',
        Team: 'PHI',
        Number: 1,
        AverageDraftPosition: 39.4,
        FantasyPoints: 329.48,
        inner_color: '#A2AAAD',
        outer_color: '#004851',
        team_name: 'Philadelphia Eagles',
    },
    {
        Name: 'Travis Etienne Jr.',
        Team: 'JAX',
        Number: 1,
        AverageDraftPosition: 40.3,
        FantasyPoints: 163.27,
        inner_color: '#000000',
        outer_color: '#006778',
        team_name: 'Jacksonville Jaguars',
    },
    {
        Name: 'DK Metcalf',
        Team: 'SEA',
        Number: 14,
        AverageDraftPosition: 41.8,
        FantasyPoints: 146.19,
        inner_color: '#69BE28',
        outer_color: '#002244',
        team_name: 'Seattle Seahawks',
    },
    {
        Name: 'Justin Herbert',
        Team: 'LAC',
        Number: 10,
        AverageDraftPosition: 42,
        FantasyPoints: 338.49,
        inner_color: '#FFC20E',
        outer_color: '#0080C6',
        team_name: 'Los Angeles Chargers',
    },
    {
        Name: 'Josh Jacobs',
        Team: 'LV',
        Number: 28,
        AverageDraftPosition: 42.7,
        FantasyPoints: 165.48,
        inner_color: '#000000',
        outer_color: '#A5ACAF',
        team_name: 'Las Vegas Raiders',
    },
    {
        Name: 'Diontae Johnson',
        Team: 'PIT',
        Number: 18,
        AverageDraftPosition: 44.1,
        FantasyPoints: 136.73,
        inner_color: '#FFB612',
        outer_color: '#000000',
        team_name: 'Pittsburgh Steelers',
    },
    {
        Name: 'DeAndre Hopkins',
        Team: 'ARI',
        Number: 10,
        AverageDraftPosition: 45.6,
        FantasyPoints: 105.6,
        inner_color: '#FFFFFF',
        outer_color: '#97233F',
        team_name: 'Arizona Cardinals',
    },
    {
        Name: 'AJ Dillon',
        Team: 'GB',
        Number: 28,
        AverageDraftPosition: 46.4,
        FantasyPoints: 153.31,
        inner_color: '#FFB612',
        outer_color: '#203731',
        team_name: 'Green Bay Packers',
    },
    {
        Name: 'Patrick Mahomes',
        Team: 'KC',
        Number: 15,
        AverageDraftPosition: 47.6,
        FantasyPoints: 345.73,
        inner_color: '#FFB612',
        outer_color: '#E31837',
        team_name: 'Kansas City Chiefs',
    },
]
